name: meno_design_system
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_gen: ^5.10.0
  flutter_hooks: ^0.21.2
  flutter_svg: ^2.0.17
  meta: ^1.16.0
  vector_graphics: ^1.1.18

dev_dependencies:
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  generate: true
  assets:
    - assets/emojis/
    - assets/gifs/
    - assets/images/
    - assets/images/brand_logos/
    - assets/images/logo/
    - assets/images/onboarding/

  fonts:
    - family: MIcons
      fonts:
        - asset: fonts/MIcons.ttf
        - asset: fonts/MIcons.main.ttf
    - family: SFProDisplay
      fonts:
        - asset: fonts/SFProDisplay_Thin.ttf
          weight: 100
        - asset: fonts/SFProDisplay_UltraLight.ttf
          weight: 200
        - asset: fonts/SFProDisplay_Light.ttf
          weight: 300
        - asset: fonts/SFProDisplay_Regular.ttf
          weight: 400
        - asset: fonts/SFProDisplay_Medium.ttf
          weight: 500
        - asset: fonts/SFProDisplay_SemiBold.ttf
          weight: 600
        - asset: fonts/SFProDisplay_Bold.ttf
          weight: 700
        - asset: fonts/SFProDisplay_Black.ttf
          weight: 800
        - asset: fonts/SFProDisplay_Heavy.ttf
          weight: 900

flutter_gen:
  output: lib/src/assets/
  integrations:
    flutter_svg: true

  assets:
    enabled: true
    outputs:
      # directory_path_enabled: true
      package_parameter_enabled: true
      class_name: MenoAssets

  fonts:
    enabled: true
    outputs:
      package_parameter_enabled: true