/// Flutter icons MIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MIcons
///      fonts:
///       - asset: fonts/MIcons.ttf
///
///
///
// ignore_for_file: constant_identifier_names, public_member_api_docs

library;

import 'package:flutter/widgets.dart';

/// Meno Custom Icons
class MIcons {
  MIcons._();

  static const _kFontFam = 'MIcons';

  static const IconData check_circle = IconData(0xe900, fontFamily: _kFontFam);
  static const IconData help_circle_1 = IconData(0xe901, fontFamily: _kFontFam);
  static const IconData marker_pin_01 = IconData(0xe902, fontFamily: _kFontFam);
  static const IconData minus_circle = IconData(0xe903, fontFamily: _kFontFam);
  static const IconData plus_circle_1 = IconData(0xe904, fontFamily: _kFontFam);
  static const IconData arrow_narrow_down_left = IconData(
    0xe905,
    fontFamily: _kFontFam,
  );
  static const IconData bell_03 = IconData(0xe906, fontFamily: _kFontFam);
  static const IconData bell_04 = IconData(0xe907, fontFamily: _kFontFam);
  static const IconData bell_off_03 = IconData(0xe908, fontFamily: _kFontFam);
  static const IconData bell_ringing_03 = IconData(
    0xe909,
    fontFamily: _kFontFam,
  );
  static const IconData bell_ringing_04 = IconData(
    0xe90a,
    fontFamily: _kFontFam,
  );
  static const IconData calendar_plus_02 = IconData(
    0xe90b,
    fontFamily: _kFontFam,
  );
  static const IconData clock_rewind = IconData(0xe90c, fontFamily: _kFontFam);
  static const IconData copy_06 = IconData(0xe90d, fontFamily: _kFontFam);
  static const IconData file_02 = IconData(0xe90e, fontFamily: _kFontFam);
  static const IconData file_minus_02 = IconData(0xe90f, fontFamily: _kFontFam);
  static const IconData file_plus_02 = IconData(0xe910, fontFamily: _kFontFam);
  static const IconData file_x_02 = IconData(0xe911, fontFamily: _kFontFam);
  static const IconData folder = IconData(0xe912, fontFamily: _kFontFam);
  static const IconData folder_lock = IconData(0xe913, fontFamily: _kFontFam);
  static const IconData folder_minus = IconData(0xe914, fontFamily: _kFontFam);
  static const IconData folder_plus = IconData(0xe915, fontFamily: _kFontFam);
  static const IconData folder_x = IconData(0xe916, fontFamily: _kFontFam);
  static const IconData format_italic = IconData(0xe917, fontFamily: _kFontFam);
  static const IconData format_list_bulleted = IconData(
    0xe918,
    fontFamily: _kFontFam,
  );
  static const IconData format_list_numbered = IconData(
    0xe919,
    fontFamily: _kFontFam,
  );
  static const IconData format_underlined = IconData(
    0xe91a,
    fontFamily: _kFontFam,
  );
  static const IconData forward_10 = IconData(0xe91b, fontFamily: _kFontFam);
  static const IconData italic_01 = IconData(0xe91c, fontFamily: _kFontFam);
  static const IconData layers_three_01 = IconData(
    0xe91d,
    fontFamily: _kFontFam,
  );
  static const IconData library_music = IconData(0xe91e, fontFamily: _kFontFam);
  static const IconData life_buoy_01 = IconData(0xe91f, fontFamily: _kFontFam);
  static const IconData log_out_03 = IconData(0xe920, fontFamily: _kFontFam);
  static const IconData moon_01 = IconData(0xe921, fontFamily: _kFontFam);
  static const IconData replay_10 = IconData(0xe922, fontFamily: _kFontFam);
  static const IconData signal_01 = IconData(0xe923, fontFamily: _kFontFam);
  static const IconData translate_02 = IconData(0xe924, fontFamily: _kFontFam);
  static const IconData underline_01 = IconData(0xe925, fontFamily: _kFontFam);
  static const IconData access_time = IconData(0xe926, fontFamily: _kFontFam);
  static const IconData announcement = IconData(0xe927, fontFamily: _kFontFam);
  static const IconData compass = IconData(0xe928, fontFamily: _kFontFam);
  static const IconData dots_horizontal = IconData(
    0xe929,
    fontFamily: _kFontFam,
  );
  static const IconData dots_vertical = IconData(0xe92a, fontFamily: _kFontFam);
  static const IconData edit_02 = IconData(0xe92b, fontFamily: _kFontFam);
  static const IconData edit_05 = IconData(0xe92c, fontFamily: _kFontFam);
  static const IconData expand_01 = IconData(0xe92d, fontFamily: _kFontFam);
  static const IconData expand_02 = IconData(0xe92e, fontFamily: _kFontFam);
  static const IconData expand_03 = IconData(0xe92f, fontFamily: _kFontFam);
  static const IconData eye_off = IconData(0xe930, fontFamily: _kFontFam);
  static const IconData hearing = IconData(0xe933, fontFamily: _kFontFam);
  static const IconData home_01 = IconData(0xe934, fontFamily: _kFontFam);
  static const IconData home_04 = IconData(0xe935, fontFamily: _kFontFam);
  static const IconData home_05 = IconData(0xe936, fontFamily: _kFontFam);
  static const IconData image = IconData(0xe937, fontFamily: _kFontFam);
  static const IconData info_circle = IconData(0xe938, fontFamily: _kFontFam);
  static const IconData link_01 = IconData(0xe939, fontFamily: _kFontFam);
  static const IconData link_02 = IconData(0xe93a, fontFamily: _kFontFam);
  static const IconData loading_01 = IconData(0xe93b, fontFamily: _kFontFam);
  static const IconData loading_02 = IconData(0xe93c, fontFamily: _kFontFam);
  static const IconData mail = IconData(0xe93d, fontFamily: _kFontFam);
  static const IconData menu_03 = IconData(0xe93e, fontFamily: _kFontFam);
  static const IconData pin = IconData(0xe93f, fontFamily: _kFontFam);
  static const IconData playlist_add = IconData(0xe940, fontFamily: _kFontFam);
  static const IconData playlist_add_check = IconData(
    0xe941,
    fontFamily: _kFontFam,
  );
  static const IconData plus_circle = IconData(0xe942, fontFamily: _kFontFam);
  static const IconData send = IconData(0xe943, fontFamily: _kFontFam);
  static const IconData star_border = IconData(0xe944, fontFamily: _kFontFam);
  static const IconData user_minus_01 = IconData(0xe945, fontFamily: _kFontFam);
  static const IconData x_circle = IconData(0xe946, fontFamily: _kFontFam);
  static const IconData x_close = IconData(0xe947, fontFamily: _kFontFam);
  static const IconData airplay = IconData(0xe948, fontFamily: _kFontFam);
  static const IconData arrow_left = IconData(0xe949, fontFamily: _kFontFam);
  static const IconData arrow_narrow_down = IconData(
    0xe94a,
    fontFamily: _kFontFam,
  );
  static const IconData arrow_narrow_right = IconData(
    0xe94b,
    fontFamily: _kFontFam,
  );
  static const IconData arrow_narrow_up = IconData(
    0xe94c,
    fontFamily: _kFontFam,
  );
  static const IconData arrow_narrow_up_right = IconData(
    0xe94d,
    fontFamily: _kFontFam,
  );
  static const IconData check = IconData(0xe94e, fontFamily: _kFontFam);
  static const IconData chevron_down = IconData(0xe94f, fontFamily: _kFontFam);
  static const IconData chevron_left = IconData(0xe950, fontFamily: _kFontFam);
  static const IconData chevron_right = IconData(0xe951, fontFamily: _kFontFam);
  static const IconData chevron_up = IconData(0xe952, fontFamily: _kFontFam);
  static const IconData eye = IconData(0xe953, fontFamily: _kFontFam);
  static const IconData fast_backward = IconData(0xe954, fontFamily: _kFontFam);
  static const IconData headphones = IconData(0xe955, fontFamily: _kFontFam);
  static const IconData heart_rounded = IconData(0xe956, fontFamily: _kFontFam);
  static const IconData help_circle = IconData(0xe957, fontFamily: _kFontFam);
  static const IconData key = IconData(0xe958, fontFamily: _kFontFam);
  static const IconData log_out = IconData(0xe959, fontFamily: _kFontFam);
  static const IconData microphone_off = IconData(
    0xe95a,
    fontFamily: _kFontFam,
  );
  static const IconData pause_circle = IconData(0xe95b, fontFamily: _kFontFam);
  static const IconData play = IconData(0xe95c, fontFamily: _kFontFam);
  static const IconData play_circle = IconData(0xe95d, fontFamily: _kFontFam);
  static const IconData plus = IconData(0xe95e, fontFamily: _kFontFam);
  static const IconData repeat = IconData(0xe95f, fontFamily: _kFontFam);
  static const IconData settings = IconData(0xe960, fontFamily: _kFontFam);
  static const IconData share = IconData(0xe961, fontFamily: _kFontFam);
  static const IconData shield = IconData(0xe962, fontFamily: _kFontFam);
  static const IconData skip_back = IconData(0xe963, fontFamily: _kFontFam);
  static const IconData skip_forward = IconData(0xe964, fontFamily: _kFontFam);
  static const IconData stop_circle = IconData(0xe965, fontFamily: _kFontFam);
  static const IconData trash = IconData(0xe966, fontFamily: _kFontFam);
  static const IconData volume_max = IconData(0xe967, fontFamily: _kFontFam);
  static const IconData volume_min = IconData(0xe968, fontFamily: _kFontFam);
  static const IconData volume_zero = IconData(0xe969, fontFamily: _kFontFam);
  static const IconData bell = IconData(0xe96a, fontFamily: _kFontFam);
  static const IconData bell_minus = IconData(0xe96b, fontFamily: _kFontFam);
  static const IconData bell_off = IconData(0xe96c, fontFamily: _kFontFam);
  static const IconData bell_ringing = IconData(0xe96d, fontFamily: _kFontFam);
  static const IconData home = IconData(0xe96e, fontFamily: _kFontFam);
  static const IconData microphone = IconData(0xe96f, fontFamily: _kFontFam);
  static const IconData search = IconData(0xe970, fontFamily: _kFontFam);
  static const IconData user = IconData(0xe971, fontFamily: _kFontFam);
  static const IconData user_check = IconData(0xe972, fontFamily: _kFontFam);
  static const IconData user_circle = IconData(0xe973, fontFamily: _kFontFam);
  static const IconData user_edit = IconData(0xe974, fontFamily: _kFontFam);
  static const IconData users = IconData(0xe975, fontFamily: _kFontFam);
  static const IconData users_check = IconData(0xe976, fontFamily: _kFontFam);
  static const IconData users_plus = IconData(0xe977, fontFamily: _kFontFam);
}
